services:
  - type: web
    name: anonymous-club-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false  # Set this in Render dashboard
      - key: JWT_SECRET
        sync: false  # Set this in Render dashboard
      - key: JWT_EXPIRE
        value: 7d
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        sync: false  # Set this in Render dashboard
      - key: EMAIL_PASS
        sync: false  # Set this in Render dashboard
      - key: FRONTEND_URL
        sync: false  # Set this to your Vercel URL