#!/bin/bash
# Render Deployment Script - Auto-configure Environment Variables

# This script helps you verify and update Render environment variables
# Run this locally to generate the correct configuration

echo "=========================================="
echo "🔧 RENDER BACKEND CONFIGURATION"
echo "=========================================="
echo ""
echo "📋 Copy these EXACT values to Render Dashboard:"
echo ""
echo "=========================================="
echo "Environment Variables to Set:"
echo "=========================================="
echo ""
echo "1. MONGODB_URI"
echo "   Value: mongodb+srv://anonymoussdmcet_db_user:BVK292@appu@cluster0.89wxvqa.mongodb.net/anonymous-club?retryWrites=true&w=majority&appName=Cluster0"
echo ""
echo "2. JWT_SECRET"
echo "   Value: anonymous_cyber_club_super_secret_key_2024_production_secure_token"
echo ""
echo "3. JWT_EXPIRE"
echo "   Value: 7d"
echo ""
echo "4. NODE_ENV"
echo "   Value: production"
echo ""
echo "5. FRONTEND_URL"
echo "   Value: https://anonymoussdmcet.vercel.app"
echo ""
echo "6. EMAIL_SERVICE"
echo "   Value: gmail"
echo ""
echo "7. EMAIL_USER"
echo "   Value: anonymous.sdmcet@gmail.com"
echo ""
echo "8. EMAIL_PASS"
echo "   Value: arnz avmv arfm lrgi"
echo ""
echo "=========================================="
echo "🚀 Steps to Update Render:"
echo "=========================================="
echo ""
echo "1. Go to: https://dashboard.render.com"
echo "2. Select: anonymous-club-backend-f2ai"
echo "3. Click: Environment tab (left sidebar)"
echo "4. Find each variable above and update/add it"
echo "5. Click: Save Changes"
echo "6. Render will auto-redeploy (2-3 minutes)"
echo ""
echo "=========================================="
echo "✅ Verification:"
echo "=========================================="
echo ""
echo "After deployment, check Render Logs for:"
echo "   ✅ MongoDB connected successfully"
echo ""
echo "Test your backend health:"
echo "   curl https://anonymous-club-backend-f2ai.onrender.com/api/health"
echo ""
echo "=========================================="
